[project]
name = "series-hmm-rnn"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["torch>=2.2", "pyyaml>=6.0"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
